from __future__ import annotations


DEFAULT_RECIPES: list[dict] = [
    {
        "id": "west-east-open-ocean",
        "name": "东西双大陆开海",
        "description": "一东一西两块大陆，中间被开阔海洋隔开，像双大陆之间的外海走廊。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.42}, {"position": "east", "size": 0.42}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["open-ocean"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "two_continents_with_rift_sea",
            "target_land_component_count": 2,
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
            "must_disconnect_pairs": [["west", "east"]],
        },
        "tags": ["split", "open-sea", "dual-continent"],
    },
    {
        "id": "west-east-inland-sea",
        "name": "东西双大陆内海",
        "description": "一东一西两块大陆，中间是被陆缘包裹的内海，只通过狭窄海峡与外海连通。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.38}, {"position": "east", "size": 0.38}],
            "mountains": [],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["inland-sea"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {
            "kind": "central_enclosed_inland_sea",
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["split", "inland-sea", "mediterranean"],
    },
    {
        "id": "single-island-continent",
        "name": "单大陆环海",
        "description": "一块四面环海的大陆，海岸线曲折但整体孤立。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.4}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["single-island"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "single_island",
            "target_land_component_count": 1,
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["island", "single-continent", "四面环海", "环海大陆"],
    },
    {
        "id": "north-south-continental-split",
        "name": "南北双大陆",
        "description": "一南一北两块大陆，中间被海域分开。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.4}, {"position": "south", "size": 0.4}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["north-south-split"],
            "profile": {"layout_template": "split_north_south", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "two_continents_with_rift_sea",
            "target_land_component_count": 2,
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
            "must_disconnect_pairs": [["north", "south"]],
        },
        "tags": ["north-south", "open-sea"],
    },
    {
        "id": "east-continent-mountains",
        "name": "东部大陆山脉",
        "description": "东部大陆有一条明显山脉，西部大陆较平缓。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.4}, {"position": "east", "size": 0.42}],
            "mountains": [{"location": "east", "height": 0.9, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "east", "length": "long"}],
            "climate_hints": ["orographic-east"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "two_continents_with_rift_sea",
            "target_land_component_count": 2,
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
            "must_disconnect_pairs": [["west", "east"]],
        },
        "tags": ["mountains", "east"],
    },
    {
        "id": "north-rim-mountains-inland",
        "name": "内海北缘山脉",
        "description": "中部内海北缘有山脉，像围绕内海的山系边界。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.36}, {"position": "east", "size": 0.36}],
            "mountains": [{"location": "north", "height": 0.88, "orientation": "east-west"}],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["inland-basin", "north-rim"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {
            "kind": "central_enclosed_inland_sea",
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["inland-sea", "north-mountains"],
    },
    {
        "id": "archipelago-tropical",
        "name": "热带群岛",
        "description": "大片群岛分布在暖湿海域，岛链密集。",
        "world_plan": {
            "continents": [],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [{"position": "center", "density": 0.78}, {"position": "southeast", "density": 0.64}],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["tropical", "archipelago"],
            "profile": {"layout_template": "archipelago", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "archipelago_chain",
            "min_land_component_count": 3,
            "target_water_component_count": 1,
            "forbid_cross_cut": False,
        },
        "tags": ["archipelago", "tropical"],
    },
    {
        "id": "supercontinent-arid-interior",
        "name": "超大陆干旱腹地",
        "description": "单一超大陆占据中心，内陆干旱，边缘湿润。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.62}],
            "mountains": [{"location": "west", "height": 0.82, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "east", "length": "short"}],
            "climate_hints": ["arid", "supercontinent"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "single_island",
            "target_land_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["supercontinent", "arid"],
    },
    {
        "id": "west-peninsula-strait",
        "name": "半岛与海峡",
        "description": "西部大陆伸出半岛，形成狭窄海峡连接内海和外海。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.44}, {"position": "east", "size": 0.34}],
            "mountains": [],
            "inland_seas": [{"position": "center", "connection": "east ocean"}],
            "island_chains": [],
            "peninsulas": [{"location": "west", "size": 0.18}],
            "river_hints": [],
            "climate_hints": ["strait"],
            "profile": {"layout_template": "mediterranean", "sea_style": "strait"},
        },
        "topology_intent": {
            "kind": "peninsula_coast",
            "target_land_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["peninsula", "strait"],
    },
    {
        "id": "cold-northland",
        "name": "寒冷北境",
        "description": "北部大片大陆，寒冷而有冰雪边缘。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.46}],
            "mountains": [{"location": "northwest", "height": 0.76, "orientation": "arc"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["frozen"],
            "profile": {"layout_template": "default", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "single_island",
            "target_land_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["north", "cold"],
    },
    {
        "id": "east-west-open-sea-north-mountains",
        "name": "开海外加北山",
        "description": "东西两块大陆被开阔海域隔开，但主要山脉位于北部高纬地带，而非某一块大陆腹地。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.41}, {"position": "east", "size": 0.41}],
            "mountains": [{"location": "north", "height": 0.86, "orientation": "east-west"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "north", "length": "short"}],
            "climate_hints": ["open-ocean", "north-rim"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "tags": ["split", "open-sea", "north-mountains", "北部有山脉", "北缘山脉"],
        "topology_intent": {
            "kind": "two_continents_with_rift_sea",
            "target_land_component_count": 2,
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
            "must_disconnect_pairs": [["west", "east"]],
        },
    },
    {
        "id": "east-west-open-sea-west-mountains",
        "name": "开海外加西山",
        "description": "东西两块大陆之间是开海，主要山脉落在西部大陆。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.43}, {"position": "east", "size": 0.39}],
            "mountains": [{"location": "west", "height": 0.88, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "west", "length": "long"}],
            "climate_hints": ["open-ocean", "west-orogen"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "two_continents_with_rift_sea",
            "target_land_component_count": 2,
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
            "must_disconnect_pairs": [["west", "east"]],
        },
        "tags": ["split", "open-sea", "west-mountains"],
    },
    {
        "id": "east-west-inland-sea-east-mountains",
        "name": "内海外加东山",
        "description": "中部是内海，东部大陆边缘有明显山脉。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.37}, {"position": "east", "size": 0.39}],
            "mountains": [{"location": "east", "height": 0.9, "orientation": "north-south"}],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "east", "length": "long"}],
            "climate_hints": ["inland-sea", "east-orogen"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {
            "kind": "central_enclosed_inland_sea",
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["inland-sea", "east-mountains"],
    },
    {
        "id": "east-west-inland-sea-south-mountains",
        "name": "内海外加南山",
        "description": "东西大陆之间是内海，南缘有一条东西向山脉。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.36}, {"position": "east", "size": 0.36}],
            "mountains": [{"location": "south", "height": 0.84, "orientation": "east-west"}],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["inland-sea", "south-rim"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {
            "kind": "central_enclosed_inland_sea",
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["inland-sea", "south-mountains"],
    },
    {
        "id": "single-island-west-peninsula",
        "name": "单岛西半岛",
        "description": "单块环海大陆向西伸出半岛，主体仍然保持岛状。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.39}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [{"location": "west", "size": 0.18}],
            "river_hints": [],
            "climate_hints": ["single-island", "west-peninsula"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "single_island",
            "target_land_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["single-island", "peninsula", "west"],
    },
    {
        "id": "single-island-east-mountains",
        "name": "单岛东山脉",
        "description": "环海单大陆，东侧靠海有山脉抬升。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.4}],
            "mountains": [{"location": "east", "height": 0.86, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}],
            "climate_hints": ["single-island", "east-orogen"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "single_island",
            "target_land_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["single-island", "east-mountains"],
    },
    {
        "id": "archipelago-northeast-chain",
        "name": "东北岛链",
        "description": "东北方向存在明显岛链，其余海域较空旷。",
        "world_plan": {
            "continents": [],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [{"position": "northeast", "density": 0.82}],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["archipelago", "northeast-chain"],
            "profile": {"layout_template": "archipelago", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "archipelago_chain",
            "min_land_component_count": 3,
            "forbid_cross_cut": False,
        },
        "tags": ["archipelago", "northeast"],
    },
    {
        "id": "archipelago-southwarm-chain",
        "name": "南方暖海群岛",
        "description": "南方暖海中散布连续群岛，北部相对空旷。",
        "world_plan": {
            "continents": [],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [{"position": "south", "density": 0.74}, {"position": "southeast", "density": 0.68}],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["archipelago", "tropical", "south-seas"],
            "profile": {"layout_template": "archipelago", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "archipelago_chain",
            "min_land_component_count": 3,
            "forbid_cross_cut": False,
        },
        "tags": ["archipelago", "south", "tropical"],
    },
    {
        "id": "supercontinent-central-mountains",
        "name": "超大陆中央山系",
        "description": "超大陆中心有一条大型山系，控制河流和气候分界。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.64}],
            "mountains": [{"location": "center", "height": 0.92, "orientation": "arc"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "west", "length": "long"}, {"region": "east", "length": "long"}],
            "climate_hints": ["supercontinent", "central-mountains"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "single_island",
            "target_land_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["supercontinent", "central-mountains"],
    },
    {
        "id": "frozen-inland-basin",
        "name": "寒冷内海盆地",
        "description": "高纬度内海被寒冷大陆包围，边缘有雪线山脉。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.35}, {"position": "east", "size": 0.35}],
            "mountains": [{"location": "north", "height": 0.8, "orientation": "east-west"}],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["frozen", "inland-sea"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {
            "kind": "central_enclosed_inland_sea",
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["frozen", "inland-sea", "north"],
    },
    {
        "id": "arid-west-east-open-ocean",
        "name": "干旱双大陆开海",
        "description": "东西两块大陆之间是开海，但两侧大陆整体偏干旱。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.4}, {"position": "east", "size": 0.4}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["open-ocean", "arid"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open", "palette_hint": "arid"},
        },
        "topology_intent": {
            "kind": "two_continents_with_rift_sea",
            "target_land_component_count": 2,
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
            "must_disconnect_pairs": [["west", "east"]],
        },
        "tags": ["open-sea", "arid", "split"],
    },
    {
        "id": "east-west-open-sea-east-mountains",
        "name": "开海外加东山",
        "description": "东西双大陆之间是开阔外海，东部大陆沿海有明显山脉。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.4}, {"position": "east", "size": 0.42}],
            "mountains": [{"location": "east", "height": 0.9, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "east", "length": "long"}],
            "climate_hints": ["open-ocean", "east-orogen"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "two_continents_with_rift_sea",
            "target_land_component_count": 2,
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
            "must_disconnect_pairs": [["west", "east"]],
        },
        "tags": ["open-sea", "east-mountains", "split", "东部大陆有山脉"],
    },
    {
        "id": "east-west-inland-sea-north-mountains",
        "name": "内海外加北山",
        "description": "东西双大陆围绕中央内海，北缘有一条山脉控制内海气候。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.36}, {"position": "east", "size": 0.37}],
            "mountains": [{"location": "north", "height": 0.88, "orientation": "east-west"}],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["inland-sea", "north-rim"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {
            "kind": "central_enclosed_inland_sea",
            "target_water_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["inland-sea", "north-mountains", "split", "北部有山脉", "中间有内海"],
    },
    {
        "id": "single-island-east-peninsula",
        "name": "单岛东半岛",
        "description": "单块环海大陆向东侧延伸出半岛，主体仍保持岛状大陆。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.39}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [{"location": "east", "size": 0.18}],
            "river_hints": [],
            "climate_hints": ["single-island", "east-peninsula"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "single_island",
            "target_land_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["single-island", "peninsula", "east", "东侧伸出半岛", "四面环海"],
    },
    {
        "id": "single-island-west-mountains",
        "name": "单岛西山脉",
        "description": "环海单大陆的西侧有山脉，整体仍是孤立大陆。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.4}],
            "mountains": [{"location": "west", "height": 0.86, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}],
            "climate_hints": ["single-island", "west-orogen"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "single_island",
            "target_land_component_count": 1,
            "forbid_cross_cut": True,
        },
        "tags": ["single-island", "west-mountains", "西侧有山脉", "四面环海"],
    },
    {
        "id": "archipelago-northeast-southwarm",
        "name": "东北岛链与南方暖海",
        "description": "南方暖海中散布群岛，东北方向另有一条更密集的岛链。",
        "world_plan": {
            "continents": [],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [{"position": "south", "density": 0.7}, {"position": "northeast", "density": 0.84}],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["archipelago", "tropical", "northeast-chain"],
            "profile": {"layout_template": "archipelago", "sea_style": "open"},
        },
        "topology_intent": {
            "kind": "archipelago_chain",
            "min_land_component_count": 3,
            "forbid_cross_cut": False,
        },
        "tags": ["archipelago", "tropical", "northeast"],
    },
    # ==== 扩充食谱 28-108 ====
    {
        "id": "single-island-north-mts",
        "name": "单岛北山脉",
        "description": "环海单大陆，北缘东西向山脉。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.4}],
            "mountains": [{"location": "north", "height": 0.84, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "south", "length": "long"}],
            "climate_hints": ["single-island", "north-mountains"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "north-mountains", "四面环海", "北部山脉"],
    },
    {
        "id": "single-island-south-mts",
        "name": "单岛南山脉",
        "description": "环海单大陆南缘有山脉。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.4}],
            "mountains": [{"location": "south", "height": 0.86, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "north", "length": "long"}],
            "climate_hints": ["single-island", "south-mountains"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "south-mountains", "四面环海", "南部有山脉"],
    },
    {
        "id": "single-island-east-penin-mts",
        "name": "单岛东半岛加山脉",
        "description": "环海单大陆东伸半岛并有东侧山脉。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.38}],
            "mountains": [{"location": "east", "height": 0.88, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [],
            "peninsulas": [{"location": "east", "size": 0.16}],
            "river_hints": [{"region": "west", "length": "long"}],
            "climate_hints": ["single-island", "east-peninsula", "east-orogen"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "peninsula", "east-mountains", "四面环海", "东侧伸出半岛"],
    },
    {
        "id": "single-island-south-penin",
        "name": "单岛南半岛",
        "description": "环海单大陆向南伸出半岛。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.39}],
            "mountains": [], "inland_seas": [], "island_chains": [],
            "peninsulas": [{"location": "south", "size": 0.16}],
            "river_hints": [], "climate_hints": ["single-island", "south-peninsula"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "peninsula", "south", "四面环海"],
    },
    {
        "id": "single-island-north-penin",
        "name": "单岛北半岛",
        "description": "环海单大陆向北伸出半岛。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.39}],
            "mountains": [], "inland_seas": [], "island_chains": [],
            "peninsulas": [{"location": "north", "size": 0.16}],
            "river_hints": [], "climate_hints": ["single-island", "north-peninsula"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "peninsula", "north", "四面环海"],
    },
    {
        "id": "single-island-west-east-penins",
        "name": "单岛东西双半岛",
        "description": "环海单大陆东西两侧各有半岛伸出。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.38}],
            "mountains": [], "inland_seas": [], "island_chains": [],
            "peninsulas": [{"location": "west", "size": 0.14}, {"location": "east", "size": 0.14}],
            "river_hints": [], "climate_hints": ["single-island", "dual-peninsula"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "peninsula", "west", "east", "四面环海"],
    },
    {
        "id": "supercontinent-tropical",
        "name": "超大陆热带",
        "description": "单一超大陆在赤道带，湿热多河。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.62}],
            "mountains": [{"location": "north", "height": 0.72, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}, {"region": "east", "length": "long"}],
            "climate_hints": ["tropical", "supercontinent", "humid"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open", "climate_zone": "tropical"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["supercontinent", "tropical", "humid"],
    },
    {
        "id": "supercontinent-north-mts",
        "name": "超大陆北缘山脉",
        "description": "超大陆北边缘有高耸山脉，阻隔寒流。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.62}],
            "mountains": [{"location": "north", "height": 0.92, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "south", "length": "long"}],
            "climate_hints": ["supercontinent", "north-mountains"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["supercontinent", "north-mountains", "北部有山脉"],
    },
    {
        "id": "supercontinent-south-mts",
        "name": "超大陆南缘山脉",
        "description": "超大陆南部有东西向山脉分隔南北。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.62}],
            "mountains": [{"location": "south", "height": 0.88, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "north", "length": "long"}],
            "climate_hints": ["supercontinent", "south-mountains"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["supercontinent", "south-mountains", "南部有山脉"],
    },
    {
        "id": "supercontinent-east-west-mts",
        "name": "超大陆东西山脉",
        "description": "超大陆东西两侧各有小山脉，中央平坦。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.63}],
            "mountains": [
                {"location": "west", "height": 0.8, "orientation": "north-south"},
                {"location": "east", "height": 0.78, "orientation": "north-south"},
            ],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}],
            "climate_hints": ["supercontinent", "dual-orogen"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["supercontinent", "east-mountains", "west-mountains"],
    },
    {
        "id": "supercontinent-west-penin",
        "name": "超大陆西半岛",
        "description": "超大陆向西伸出半岛。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.6}],
            "mountains": [], "inland_seas": [], "island_chains": [],
            "peninsulas": [{"location": "west", "size": 0.2}],
            "river_hints": [], "climate_hints": ["supercontinent", "west-peninsula"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["supercontinent", "peninsula", "west"],
    },
    {
        "id": "supercontinent-east-penin",
        "name": "超大陆东半岛",
        "description": "超大陆向东伸出半岛。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.6}],
            "mountains": [], "inland_seas": [], "island_chains": [],
            "peninsulas": [{"location": "east", "size": 0.2}],
            "river_hints": [], "climate_hints": ["supercontinent", "east-peninsula"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["supercontinent", "peninsula", "east"],
    },
    {
        "id": "ns-open-sea-east-mts",
        "name": "南北双大陆东山脉",
        "description": "南北大陆开海，东部有山脉。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.39}, {"position": "south", "size": 0.4}],
            "mountains": [{"location": "east", "height": 0.88, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "east", "length": "long"}],
            "climate_hints": ["north-south-split", "east-orogen"],
            "profile": {"layout_template": "split_north_south", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["north", "south"]]},
        "tags": ["north-south", "open-sea", "east-mountains"],
    },
    {
        "id": "ns-open-sea-west-mts",
        "name": "南北双大陆西山脉",
        "description": "南北大陆开海，西部大陆有山脉。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.39}, {"position": "south", "size": 0.4}],
            "mountains": [{"location": "west", "height": 0.88, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "west", "length": "long"}],
            "climate_hints": ["north-south-split", "west-orogen"],
            "profile": {"layout_template": "split_north_south", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["north", "south"]]},
        "tags": ["north-south", "open-sea", "west-mountains"],
    },
    {
        "id": "ns-open-sea-north-mts",
        "name": "南北双大陆北山脉",
        "description": "南北双大陆开海，北部大陆边缘有东西向山脉。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.4}, {"position": "south", "size": 0.39}],
            "mountains": [{"location": "north", "height": 0.9, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "north", "length": "short"}],
            "climate_hints": ["north-south-split", "north-rim"],
            "profile": {"layout_template": "split_north_south", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["north", "south"]]},
        "tags": ["north-south", "open-sea", "north-mountains", "北部山脉"],
    },
    {
        "id": "ns-open-sea-south-mts",
        "name": "南北双大陆南山脉",
        "description": "南北双大陆开海，南部大陆有东西向山脉。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.39}, {"position": "south", "size": 0.4}],
            "mountains": [{"location": "south", "height": 0.88, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "south", "length": "long"}],
            "climate_hints": ["north-south-split", "south-rim"],
            "profile": {"layout_template": "split_north_south", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["north", "south"]]},
        "tags": ["north-south", "open-sea", "south-mountains", "南部有山脉"],
    },
    {
        "id": "ew-open-sea-south-mts",
        "name": "东西开海南山脉",
        "description": "东西双大陆隔离，南部山脉。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.39}, {"position": "east", "size": 0.41}],
            "mountains": [{"location": "south", "height": 0.88, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "south", "length": "short"}],
            "climate_hints": ["open-ocean", "south-rim"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "open-sea", "south-mountains", "南部有山脉"],
    },
    {
        "id": "ew-open-sea-east-penin",
        "name": "东西开海东半岛",
        "description": "东西大陆开海，东大陆东侧伸出半岛。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.39}, {"position": "east", "size": 0.41}],
            "mountains": [], "inland_seas": [], "island_chains": [],
            "peninsulas": [{"location": "east", "size": 0.18}],
            "river_hints": [], "climate_hints": ["open-ocean", "east-peninsula"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "open-sea", "peninsula", "east"],
    },
    {
        "id": "ew-open-sea-west-penin",
        "name": "东西开海西半岛",
        "description": "东西大陆开海，西大陆西侧伸出半岛。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.41}, {"position": "east", "size": 0.39}],
            "mountains": [], "inland_seas": [], "island_chains": [],
            "peninsulas": [{"location": "west", "size": 0.18}],
            "river_hints": [], "climate_hints": ["open-ocean", "west-peninsula"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "open-sea", "peninsula", "west"],
    },
    {
        "id": "ew-inland-sea-east-penin",
        "name": "内海双大陆东半岛",
        "description": "东西大陆围绕内海，东大陆东侧有半岛。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.36}, {"position": "east", "size": 0.37}],
            "mountains": [],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [{"location": "east", "size": 0.16}],
            "river_hints": [], "climate_hints": ["inland-sea", "east-peninsula"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {"kind": "central_enclosed_inland_sea", "target_water_component_count": 1, "forbid_cross_cut": True},
        "tags": ["inland-sea", "peninsula", "east", "中间有内海"],
    },
    {
        "id": "ew-inland-sea-west-penin",
        "name": "内海双大陆西半岛",
        "description": "东西大陆围绕内海，西大陆西侧有半岛。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.37}, {"position": "east", "size": 0.36}],
            "mountains": [],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [{"location": "west", "size": 0.16}],
            "river_hints": [], "climate_hints": ["inland-sea", "west-peninsula"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {"kind": "central_enclosed_inland_sea", "target_water_component_count": 1, "forbid_cross_cut": True},
        "tags": ["inland-sea", "peninsula", "west", "中间有内海"],
    },
    {
        "id": "ew-inland-sea-dual-mts",
        "name": "内海双大陆双山脉",
        "description": "东西大陆围绕内海各有一条山脉。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.35}, {"position": "east", "size": 0.36}],
            "mountains": [{"location": "west", "height": 0.82, "orientation": "north-south"}, {"location": "east", "height": 0.84, "orientation": "north-south"}],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "west", "length": "long"}, {"region": "east", "length": "long"}],
            "climate_hints": ["inland-sea", "dual-orogen"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {"kind": "central_enclosed_inland_sea", "target_water_component_count": 1, "forbid_cross_cut": True},
        "tags": ["inland-sea", "east-mountains", "west-mountains", "split"],
    },
    {
        "id": "ew-open-sea-arid",
        "name": "东西双大陆开海干旱",
        "description": "东西大陆被开海隔开，整体干旱。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.42}, {"position": "east", "size": 0.42}],
            "mountains": [], "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "north", "length": "short"}, {"region": "south", "length": "short"}],
            "climate_hints": ["open-ocean", "arid"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open", "climate_zone": "arid"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "open-sea", "arid", "干旱"],
    },
    {
        "id": "ew-open-sea-cold",
        "name": "东西双大陆严寒",
        "description": "东西大陆被开海隔开，高纬严寒覆盖冻土。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.41}, {"position": "east", "size": 0.41}],
            "mountains": [{"location": "north", "height": 0.76, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [], "climate_hints": ["open-ocean", "frozen", "polar"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open", "climate_zone": "polar"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "open-sea", "frozen", "寒冷"],
    },
    {
        "id": "three-continents-open",
        "name": "三大陆开海",
        "description": "三块大陆分散，被海域隔开。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.28}, {"position": "east", "size": 0.28}, {"position": "south", "size": 0.24}],
            "mountains": [], "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [], "climate_hints": ["open-ocean", "multi-continent"],
            "profile": {"layout_template": "multi_continent", "sea_style": "open"},
        },
        "topology_intent": {"kind": "multi_continent", "min_land_component_count": 3, "forbid_cross_cut": False},
        "tags": ["split", "open-sea", "multi", "多块大陆"],
    },
    {
        "id": "three-continents-east-mts",
        "name": "三大陆东山",
        "description": "三块大陆，东部有纵向山脉。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.27}, {"position": "east", "size": 0.29}, {"position": "north", "size": 0.25}],
            "mountains": [{"location": "east", "height": 0.9, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "east", "length": "long"}],
            "climate_hints": ["multi-continent", "east-orogen"],
            "profile": {"layout_template": "multi_continent", "sea_style": "open"},
        },
        "topology_intent": {"kind": "multi_continent", "min_land_component_count": 3, "forbid_cross_cut": False},
        "tags": ["split", "open-sea", "multi", "east-mountains", "东部有山脉"],
    },
    {
        "id": "four-continents-scatter",
        "name": "四大陆分散",
        "description": "东西南北各有一块大陆，被广阔海域隔开。",
        "world_plan": {
            "continents": [
                {"position": "north", "size": 0.22}, {"position": "south", "size": 0.22},
                {"position": "west", "size": 0.22}, {"position": "east", "size": 0.22},
            ],
            "mountains": [], "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [], "climate_hints": ["open-ocean", "multi-continent"],
            "profile": {"layout_template": "multi_continent", "sea_style": "open"},
        },
        "topology_intent": {"kind": "multi_continent", "min_land_component_count": 4, "forbid_cross_cut": False},
        "tags": ["split", "open-sea", "multi", "分散大陆"],
    },
    {
        "id": "archipelago-dense-north",
        "name": "北部密集群岛",
        "description": "北部海域密集散布群岛。",
        "world_plan": {
            "continents": [], "mountains": [], "inland_seas": [],
            "island_chains": [{"position": "north", "density": 0.82}, {"position": "northwest", "density": 0.74}],
            "peninsulas": [], "river_hints": [], "climate_hints": ["archipelago", "north-seas"],
            "profile": {"layout_template": "archipelago", "sea_style": "open"},
        },
        "topology_intent": {"kind": "archipelago_chain", "min_land_component_count": 3, "target_water_component_count": 1, "forbid_cross_cut": False},
        "tags": ["archipelago", "north"],
    },
    {
        "id": "archipelago-global-ring",
        "name": "环球岛链",
        "description": "群岛呈环状围绕中央水域，如太平洋火环。",
        "world_plan": {
            "continents": [], "mountains": [], "inland_seas": [],
            "island_chains": [
                {"position": "nw", "density": 0.64}, {"position": "ne", "density": 0.66},
                {"position": "sw", "density": 0.62}, {"position": "se", "density": 0.64},
            ],
            "peninsulas": [], "river_hints": [], "climate_hints": ["archipelago", "ring-chain"],
            "profile": {"layout_template": "archipelago", "sea_style": "open"},
        },
        "topology_intent": {"kind": "archipelago_chain", "min_land_component_count": 8, "forbid_cross_cut": False},
        "tags": ["archipelago", "ring", "岛弧"],
    },
    {
        "id": "archipelago-temperate",
        "name": "温带群岛",
        "description": "温带海域群岛，气候温和。",
        "world_plan": {
            "continents": [], "mountains": [], "inland_seas": [],
            "island_chains": [{"position": "center", "density": 0.6}],
            "peninsulas": [], "river_hints": [], "climate_hints": ["archipelago", "temperate"],
            "profile": {"layout_template": "archipelago", "sea_style": "open", "climate_zone": "temperate"},
        },
        "topology_intent": {"kind": "archipelago_chain", "min_land_component_count": 3, "forbid_cross_cut": False},
        "tags": ["archipelago", "temperate"],
    },
    {
        "id": "archipelago-polar",
        "name": "极地冰岛",
        "description": "极地海域群岛，被冰雪覆盖。",
        "world_plan": {
            "continents": [], "mountains": [], "inland_seas": [],
            "island_chains": [{"position": "north", "density": 0.64}],
            "peninsulas": [], "river_hints": [], "climate_hints": ["archipelago", "frozen", "polar"],
            "profile": {"layout_template": "archipelago", "sea_style": "open", "climate_zone": "polar"},
        },
        "topology_intent": {"kind": "archipelago_chain", "min_land_component_count": 3, "forbid_cross_cut": False},
        "tags": ["archipelago", "polar", "frozen", "极地"],
    },
    {
        "id": "mediterranean-temperate",
        "name": "温润地中海",
        "description": "中部内海被温润大陆包围，气候温和湿润。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.36}, {"position": "east", "size": 0.36}],
            "mountains": [{"location": "north", "height": 0.7, "orientation": "east-west"}],
            "inland_seas": [{"position": "center", "connection": "west strait"}],
            "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "north", "length": "medium"}, {"region": "south", "length": "medium"}],
            "climate_hints": ["inland-sea", "temperate", "humid"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland", "climate_zone": "temperate"},
        },
        "topology_intent": {"kind": "central_enclosed_inland_sea", "target_water_component_count": 1, "forbid_cross_cut": True},
        "tags": ["inland-sea", "temperate", "humid", "中间有内海"],
    },
    {
        "id": "mediterranean-arid-south",
        "name": "干旱南地中海",
        "description": "中央内海南部干旱有沙漠，北部湿润。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.35}, {"position": "east", "size": 0.36}],
            "mountains": [{"location": "south", "height": 0.78, "orientation": "east-west"}],
            "inland_seas": [{"position": "center", "connection": "east strait"}],
            "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "north", "length": "long"}],
            "climate_hints": ["inland-sea", "arid-south"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {"kind": "central_enclosed_inland_sea", "target_water_component_count": 1, "forbid_cross_cut": True},
        "tags": ["inland-sea", "arid", "south-mountains", "干旱", "中间有内海"],
    },
    {
        "id": "mediterranean-volcanic",
        "name": "地中海火山带",
        "description": "中央内海东西两岸各有一条年轻造山带，火山活跃。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.34}, {"position": "east", "size": 0.35}],
            "mountains": [{"location": "west", "height": 0.9, "orientation": "arc"}, {"location": "east", "height": 0.92, "orientation": "arc"}],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "west", "length": "short"}, {"region": "east", "length": "short"}],
            "climate_hints": ["inland-sea", "volcanic"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {"kind": "central_enclosed_inland_sea", "target_water_component_count": 1, "forbid_cross_cut": True},
        "tags": ["inland-sea", "mountains", "volcano", "火山"],
    },
    {
        "id": "peninsula-world-east",
        "name": "东部半岛世界",
        "description": "东部大陆向海洋延伸多条半岛。",
        "world_plan": {
            "continents": [{"position": "east", "size": 0.48}],
            "mountains": [{"location": "east", "height": 0.82, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [{"position": "west", "density": 0.48}],
            "peninsulas": [{"location": "east", "size": 0.14}, {"location": "southeast", "size": 0.12}],
            "river_hints": [{"region": "east", "length": "long"}],
            "climate_hints": ["peninsula", "monsoon"],
            "profile": {"layout_template": "default", "sea_style": "open"},
        },
        "topology_intent": {"kind": "peninsula_coast", "target_land_component_count": 2, "forbid_cross_cut": True},
        "tags": ["peninsula", "east", "monsoon"],
    },
    {
        "id": "rift-valley-continent",
        "name": "裂谷大陆",
        "description": "超大陆中间有裂谷带贯穿。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.6}],
            "mountains": [{"location": "center", "height": 0.74, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}],
            "climate_hints": ["rift", "central-depression"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open", "terrain_style": "rift"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["supercontinent", "rift", "valley", "裂谷"],
    },
    {
        "id": "coastal-mountain-world",
        "name": "沿海山脉世界",
        "description": "两块大陆靠海一侧均有山脉，内陆平坦。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.39}, {"position": "east", "size": 0.39}],
            "mountains": [{"location": "west", "height": 0.84, "orientation": "north-south"}, {"location": "east", "height": 0.86, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "west", "length": "short"}, {"region": "east", "length": "short"}],
            "climate_hints": ["open-ocean", "coastal-mountains"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "open-sea", "west-mountains", "east-mountains"],
    },
    {
        "id": "central-lake-continent",
        "name": "中央大湖大陆",
        "description": "环海单大陆中部有大型内陆湖，多条河流汇聚。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.41}],
            "mountains": [{"location": "center", "height": 0.56, "orientation": "arc"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}, {"region": "north", "length": "long"}, {"region": "south", "length": "long"}],
            "climate_hints": ["single-island", "lake-basin"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "terrain_style": "lake-basin"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "lake", "河流", "四面环海"],
    },
    {
        "id": "glacier-fjord-north",
        "name": "冰川峡湾北境",
        "description": "北部大陆海岸被冰川侵蚀成深陷峡湾群。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.44}],
            "mountains": [{"location": "northeast", "height": 0.82, "orientation": "arc"}],
            "inland_seas": [], "island_chains": [],
            "peninsulas": [{"location": "northwest", "size": 0.12}],
            "river_hints": [{"region": "north", "length": "short"}],
            "climate_hints": ["frozen", "fjord"],
            "profile": {"layout_template": "default", "sea_style": "open", "climate_zone": "polar", "terrain_style": "fjord"},
        },
        "topology_intent": {"kind": "peninsula_coast", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["north", "frozen", "fjord", "冰川"],
    },
    {
        "id": "tropical-rainforest-pangea",
        "name": "热带雨林超大陆",
        "description": "超大陆覆盖热带雨林，河流密布。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.62}],
            "mountains": [{"location": "center", "height": 0.6, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}, {"region": "east", "length": "long"}, {"region": "west", "length": "long"}],
            "climate_hints": ["tropical", "humid", "supercontinent"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open", "climate_zone": "tropical"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["supercontinent", "tropical", "forest", "多雨"],
    },
    {
        "id": "spine-mountain-continent",
        "name": "大陆脊梁山脉",
        "description": "单大陆中心有一条南北向超级山脉，如大陆脊梁。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.44}],
            "mountains": [{"location": "center", "height": 0.94, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "west", "length": "long"}, {"region": "east", "length": "long"}],
            "climate_hints": ["single-island", "spine-ridge"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "central-mountains", "山脉纵贯", "四面环海"],
    },
    {
        "id": "transverse-mountain-continent",
        "name": "横向山脉大陆",
        "description": "大陆中部东西向山脉，分割南北流域。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.45}],
            "mountains": [{"location": "center", "height": 0.9, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "north", "length": "long"}, {"region": "south", "length": "long"}],
            "climate_hints": ["single-island", "transverse-range"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "central-mountains", "山脉横贯", "四面环海"],
    },
    {
        "id": "island-double-opposing",
        "name": "双子海岛大陆",
        "description": "东西两块四面环海的大陆如独立海岛，中间海峡。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.38}, {"position": "east", "size": 0.38}],
            "mountains": [], "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [], "climate_hints": ["single-island", "dual-island", "narrow-strait"],
            "profile": {"layout_template": "split_east_west", "sea_style": "strait"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "strait", "dual-continent", "海峡"],
    },
    {
        "id": "desert-planet-super",
        "name": "沙漠星球超大陆",
        "description": "绝大部分陆地集中在单一超大陆，极度干旱大沙漠。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.66}],
            "mountains": [{"location": "north", "height": 0.7, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "south", "length": "short"}],
            "climate_hints": ["arid", "supercontinent", "desert"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open", "climate_zone": "arid", "palette_hint": "desert"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["supercontinent", "arid", "desert", "沙漠"],
    },
    {
        "id": "ocean-world-fragments",
        "name": "海洋世界碎片",
        "description": "全球海洋占绝大多数，只有少量岛屿碎片。",
        "world_plan": {
            "continents": [], "mountains": [], "inland_seas": [],
            "island_chains": [{"position": "south", "density": 0.42}, {"position": "northeast", "density": 0.36}],
            "peninsulas": [], "river_hints": [], "climate_hints": ["archipelago", "ocean-world"],
            "profile": {"layout_template": "archipelago", "sea_style": "open"},
        },
        "topology_intent": {"kind": "archipelago_chain", "min_land_component_count": 2, "forbid_cross_cut": False, "target_water_component_count": 1},
        "tags": ["archipelago", "ocean", "sparse", "海洋"],
    },
    {
        "id": "ew-asymmetric-large-east",
        "name": "不对称大陆东大",
        "description": "东西大陆被海隔开，东部大陆比西大。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.3}, {"position": "east", "size": 0.51}],
            "mountains": [{"location": "east", "height": 0.82, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [{"position": "southwest", "density": 0.52}],
            "peninsulas": [], "river_hints": [{"region": "east", "length": "long"}],
            "climate_hints": ["open-ocean", "asymmetric"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "open-sea", "asymmetric"],
    },
    {
        "id": "ew-asymmetric-large-west",
        "name": "不对称大陆西大",
        "description": "东西大陆被海隔开，西部大陆比东大。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.51}, {"position": "east", "size": 0.3}],
            "mountains": [{"location": "west", "height": 0.84, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [{"position": "southeast", "density": 0.5}],
            "peninsulas": [], "river_hints": [{"region": "west", "length": "long"}],
            "climate_hints": ["open-ocean", "asymmetric"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "open-sea", "asymmetric"],
    },
    {
        "id": "single-island-central-depression",
        "name": "中央盆地岛大陆",
        "description": "环海单大陆中心有大盆地，四周有低矮丘陵。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.42}],
            "mountains": [{"location": "center", "height": 0.48, "orientation": "arc"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}],
            "climate_hints": ["single-island", "basin"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "terrain_style": "depression"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "basin", "盆地", "四面环海"],
    },
    {
        "id": "highland-plateau-continent",
        "name": "高原大陆",
        "description": "环海单大陆整体地势高，高原台地，边缘陡峭入海。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.4}],
            "mountains": [{"location": "center", "height": 0.8, "orientation": "arc"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "west", "length": "long"}, {"region": "east", "length": "long"}],
            "climate_hints": ["single-island", "plateau"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "terrain_style": "plateau"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "plateau", "高原", "四面环海"],
    },
    {
        "id": "swamp-wetland-continent",
        "name": "沼泽湿原大陆",
        "description": "环海单大陆低洼湿润，密布沼泽湿地。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.41}],
            "mountains": [], "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}, {"region": "north", "length": "long"}, {"region": "south", "length": "long"}],
            "climate_hints": ["single-island", "swamp", "humid"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "climate_zone": "humid"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "swamp", "wet", "四面环海"],
    },
    {
        "id": "savanna-grassland-continent",
        "name": "稀树草原大陆",
        "description": "环海单大陆以稀树草原为主，干湿季交替。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.42}],
            "mountains": [{"location": "north", "height": 0.64, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}],
            "climate_hints": ["single-island", "savanna", "temperate"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "climate_zone": "temperate"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "grassland", "temperate", "四面环海"],
    },
    {
        "id": "ns-inland-sea",
        "name": "南北双大陆内海",
        "description": "南北两块大陆包围中部内海。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.37}, {"position": "south", "size": 0.37}],
            "mountains": [],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [], "peninsulas": [],
            "river_hints": [], "climate_hints": ["inland-sea", "north-south-split"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {"kind": "central_enclosed_inland_sea", "target_water_component_count": 1, "forbid_cross_cut": True},
        "tags": ["inland-sea", "north-south", "split"],
    },
    {
        "id": "ew-open-sea-dual-penin",
        "name": "东西开海双半岛",
        "description": "东西大陆被海隔开，两侧各向对方伸半岛。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.38}, {"position": "east", "size": 0.38}],
            "mountains": [], "inland_seas": [], "island_chains": [],
            "peninsulas": [{"location": "west", "size": 0.14}, {"location": "east", "size": 0.14}],
            "river_hints": [], "climate_hints": ["open-ocean", "dual-peninsula"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "open-sea", "peninsula", "dual-continent"],
    },
    {
        "id": "ns-tropical-cold",
        "name": "南北气候分异大陆",
        "description": "北大陆寒冷有冻土，南大陆热带，中间海分隔。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.41}, {"position": "south", "size": 0.42}],
            "mountains": [{"location": "north", "height": 0.72, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [{"position": "center", "density": 0.42}],
            "peninsulas": [], "river_hints": [{"region": "south", "length": "long"}],
            "climate_hints": ["frozen", "tropical", "contrast"],
            "profile": {"layout_template": "split_north_south", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["north", "south"]]},
        "tags": ["north-south", "open-sea", "frozen", "tropical"],
    },
    {
        "id": "single-island-se-arch",
        "name": "单岛东南群岛",
        "description": "环海单大陆为主体，东南散布密集岛链。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.38}],
            "mountains": [], "inland_seas": [],
            "island_chains": [{"position": "southeast", "density": 0.76}],
            "peninsulas": [], "river_hints": [],
            "climate_hints": ["single-island", "archipelago"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 2, "forbid_cross_cut": True},
        "tags": ["single-island", "archipelago", "southeast", "四面环海"],
    },
    {
        "id": "single-island-nw-arch",
        "name": "单岛西北群岛",
        "description": "环海单大陆为主体，西北散布密集群岛。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.38}],
            "mountains": [], "inland_seas": [],
            "island_chains": [{"position": "northwest", "density": 0.78}],
            "peninsulas": [], "river_hints": [],
            "climate_hints": ["single-island", "archipelago"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 2, "forbid_cross_cut": True},
        "tags": ["single-island", "archipelago", "northwest", "四面环海"],
    },
    {
        "id": "ew-open-sea-archipelago",
        "name": "东西双大陆加群岛",
        "description": "东西大陆被开海隔开，海中有群岛散布。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.39}, {"position": "east", "size": 0.39}],
            "mountains": [], "inland_seas": [],
            "island_chains": [{"position": "center", "density": 0.58}],
            "peninsulas": [], "river_hints": [],
            "climate_hints": ["open-ocean", "archipelago"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 3, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "open-sea", "archipelago"],
    },
    {
        "id": "ew-inland-sea-archipelago",
        "name": "内海双大陆加群岛",
        "description": "东西大陆包绕内海，内海中有群岛散布。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.35}, {"position": "east", "size": 0.35}],
            "mountains": [],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [{"position": "center", "density": 0.46}],
            "peninsulas": [], "river_hints": [],
            "climate_hints": ["inland-sea", "archipelago"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {"kind": "central_enclosed_inland_sea", "target_water_component_count": 1, "forbid_cross_cut": True},
        "tags": ["inland-sea", "archipelago", "split"],
    },
    {
        "id": "supercontinent-east-coast-mts",
        "name": "超大陆东海山脉",
        "description": "超大陆东海岸绵延南北向大山脉。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.62}],
            "mountains": [{"location": "east", "height": 0.92, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "west", "length": "long"}],
            "climate_hints": ["supercontinent", "east-orogen"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["supercontinent", "east-mountains"],
    },
    {
        "id": "single-island-arid",
        "name": "单岛干旱大陆",
        "description": "四面环海但副热带高压带，腹地为大片沙漠。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.41}],
            "mountains": [{"location": "west", "height": 0.7, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "east", "length": "short"}],
            "climate_hints": ["single-island", "arid", "desert"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "climate_zone": "arid"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "arid", "desert", "干旱", "四面环海"],
    },
    {
        "id": "monsoon-east-coast",
        "name": "季风东海岸大陆",
        "description": "单大陆东海岸受季风降雨充沛，西侧有雨影沙漠。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.42}],
            "mountains": [{"location": "east", "height": 0.82, "orientation": "north-south"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "east", "length": "long"}],
            "climate_hints": ["monsoon", "east-orogen"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "monsoon", "east-mountains", "季风", "四面环海"],
    },
    {
        "id": "coral-reef-atoll",
        "name": "环礁世界",
        "description": "热带海洋以环礁、珊瑚礁低平岛屿为特色。",
        "world_plan": {
            "continents": [], "mountains": [], "inland_seas": [],
            "island_chains": [{"position": "center", "density": 0.62}, {"position": "south", "density": 0.56}],
            "peninsulas": [], "river_hints": [],
            "climate_hints": ["archipelago", "tropical", "reef"],
            "profile": {"layout_template": "archipelago", "sea_style": "open", "climate_zone": "tropical", "terrain_style": "reef"},
        },
        "topology_intent": {"kind": "archipelago_chain", "min_land_component_count": 5, "forbid_cross_cut": False},
        "tags": ["archipelago", "tropical", "reef", "珊瑚礁"],
    },
    {
        "id": "delta-coast-continent",
        "name": "三角洲海岸大陆",
        "description": "大河入海口形成多条三角洲，冲积平原密集。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.42}],
            "mountains": [{"location": "center", "height": 0.58, "orientation": "arc"}],
            "inland_seas": [], "island_chains": [],
            "peninsulas": [{"location": "south", "size": 0.12}],
            "river_hints": [{"region": "center", "length": "long"}, {"region": "north", "length": "long"}],
            "climate_hints": ["river-system", "delta-coast"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "terrain_style": "delta"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["single-island", "river", "delta", "三角洲", "四面环海"],
    },
    {
        "id": "ns-dual-mountains",
        "name": "南北双大陆双山脉",
        "description": "南北大陆各有独立山脉，中心海域分隔。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.38}, {"position": "south", "size": 0.4}],
            "mountains": [{"location": "north", "height": 0.84, "orientation": "east-west"}, {"location": "south", "height": 0.82, "orientation": "east-west"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "north", "length": "medium"}, {"region": "south", "length": "medium"}],
            "climate_hints": ["north-south-split", "dual-orogen"],
            "profile": {"layout_template": "split_north_south", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["north", "south"]]},
        "tags": ["north-south", "open-sea", "north-mountains", "south-mountains"],
    },
    {
        "id": "volcanic-arc-peninsular",
        "name": "火山弧半岛",
        "description": "东部大陆边缘火山岛弧半岛，有活跃火山锥。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.35}, {"position": "east", "size": 0.42}],
            "mountains": [{"location": "east", "height": 0.9, "orientation": "arc"}],
            "inland_seas": [],
            "island_chains": [{"position": "northeast", "density": 0.72}],
            "peninsulas": [{"location": "east", "size": 0.16}],
            "river_hints": [{"region": "east", "length": "short"}],
            "climate_hints": ["open-ocean", "volcanic"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 3, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "open-sea", "volcano", "east-mountains", "火山"],
    },
    {
        "id": "isthmus-land-bridge",
        "name": "陆桥世界",
        "description": "两块大陆被狭窄地峡相连，海洋分隔两边。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.36}, {"position": "south", "size": 0.36}],
            "mountains": [], "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [], "climate_hints": ["isthmus", "land-bridge"],
            "profile": {"layout_template": "split_north_south", "sea_style": "strait"},
        },
        "topology_intent": {"kind": "peninsula_coast", "target_land_component_count": 1, "target_water_component_count": 2, "forbid_cross_cut": True},
        "tags": ["connection", "isthmus", "strait", "陆桥"],
    },
    {
        "id": "supercontinent-great-rivers",
        "name": "超大陆大河系统",
        "description": "超大陆内部大河放射状从中央山脉流向边缘入海。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.64}],
            "mountains": [{"location": "center", "height": 0.9, "orientation": "arc"}],
            "inland_seas": [], "island_chains": [], "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}, {"region": "east", "length": "long"}, {"region": "west", "length": "long"}, {"region": "south", "length": "long"}],
            "climate_hints": ["supercontinent", "river-system"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["supercontinent", "central-mountains", "river", "河流"],
    },
    {
        "id": "asia-mimic",
        "name": "亚洲形大陆",
        "description": "单大陆主体向北扩展宽广，南部海域群岛如东南亚。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.48, "shape_hint": "north-expanding"}],
            "mountains": [{"location": "central", "height": 0.86, "orientation": "east-west"}, {"location": "south", "height": 0.76, "orientation": "east-west"}],
            "inland_seas": [],
            "island_chains": [{"position": "southeast", "density": 0.8}],
            "peninsulas": [{"location": "south", "size": 0.14}, {"location": "east", "size": 0.14}],
            "river_hints": [{"region": "south", "length": "long"}, {"region": "east", "length": "long"}, {"region": "center", "length": "long"}],
            "climate_hints": ["monsoon", "river-system"],
            "profile": {"layout_template": "default", "sea_style": "open"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 2, "forbid_cross_cut": True},
        "tags": ["peninsula", "archipelago", "southeast", "monsoon", "河流"],
    },
    {
        "id": "africa-europe-mimic",
        "name": "非欧形双大陆",
        "description": "北部大陆较小有山脉，南部大，中间隔如地中海。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.3}, {"position": "south", "size": 0.39}],
            "mountains": [{"location": "north", "height": 0.9, "orientation": "east-west"}],
            "inland_seas": [{"position": "center", "connection": "west strait"}],
            "island_chains": [{"position": "center", "density": 0.52}],
            "peninsulas": [{"location": "south", "size": 0.1}],
            "river_hints": [{"region": "north", "length": "long"}, {"region": "south", "length": "long"}],
            "climate_hints": ["inland-sea", "north-mountains"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "topology_intent": {"kind": "central_enclosed_inland_sea", "target_water_component_count": 1, "forbid_cross_cut": True},
        "tags": ["inland-sea", "north-mountains", "dual-continent", "中间有内海"],
    },
    {
        "id": "megacontinent-central-desert",
        "name": "超大陆中央沙漠",
        "description": "超大陆中心为大沙漠，边缘山区和高地围绕。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.66}],
            "mountains": [{"location": "north", "height": 0.85, "orientation": "east-west"}, {"location": "south", "height": 0.82, "orientation": "east-west"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [{"location": "east", "size": 0.12}],
            "river_hints": [{"region": "south", "length": "medium"}],
            "climate_hints": ["supercontinent", "arid", "desert-core"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open", "climate_zone": "arid"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["supercontinent", "arid", "desert", "超大陆", "沙漠"],
    },
    {
        "id": "east-west-mid-ocean-ridge",
        "name": "洋中脊分隔",
        "description": "东西大陆被大洋中脊（海底山脉链）分隔。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.4}, {"position": "east", "size": 0.4}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [{"position": "center", "density": 0.24}],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["open-ocean", "mid-ocean-ridge"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open", "terrain_style": "mid-ocean-ridge"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 3, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["west", "east"]]},
        "tags": ["split", "open-sea", "mid-ocean-ridge"],
    },
    {
        "id": "ring-world-four-continents",
        "name": "环状四大陆",
        "description": "四块大陆围绕中央海洋呈环状分布，中央为开阔深海。",
        "world_plan": {
            "continents": [
                {"position": "north", "size": 0.2}, {"position": "south", "size": 0.2},
                {"position": "west", "size": 0.2}, {"position": "east", "size": 0.2},
            ],
            "mountains": [],
            "inland_seas": [{"position": "center", "connection": "open ocean"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["ring-world", "central-ocean"],
            "profile": {"layout_template": "archipelago", "sea_style": "open"},
        },
        "topology_intent": {"kind": "enclosed_ocean", "target_land_component_count": 4, "target_water_component_count": 2, "forbid_cross_cut": False},
        "tags": ["ring", "multi-continent", "ocean"],
    },
    {
        "id": "southland-temperate-mts",
        "name": "南陆温带山地",
        "description": "南部温带大块陆地，腹地有丘陵河网。",
        "world_plan": {
            "continents": [{"position": "south", "size": 0.44}],
            "mountains": [{"location": "southwest", "height": 0.72, "orientation": "arc"}],
            "inland_seas": [],
            "island_chains": [{"position": "northeast", "density": 0.42}],
            "peninsulas": [{"location": "southeast", "size": 0.13}],
            "river_hints": [{"region": "south", "length": "long"}],
            "climate_hints": ["temperate", "hilly"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "climate_zone": "temperate"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 2, "forbid_cross_cut": True},
        "tags": ["south", "temperate", "hilly"],
    },
    {
        "id": "westland-tropical-mts-rivers",
        "name": "西陆热带多河山脉",
        "description": "西部炎热大陆有山系，多处大河奔流入海。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.46}],
            "mountains": [{"location": "west", "height": 0.88, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [{"position": "south", "density": 0.5}],
            "peninsulas": [],
            "river_hints": [{"region": "west", "length": "long"}, {"region": "south", "length": "long"}],
            "climate_hints": ["tropical", "monsoon"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "climate_zone": "tropical"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 2, "forbid_cross_cut": True},
        "tags": ["west", "tropical", "mountains", "河流"],
    },
    {
        "id": "tundra-boreal-continent",
        "name": "苔原大陆",
        "description": "极地苔原大陆遍布冻土丘和冰缘地貌，低矮植被稀疏。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.46}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "center", "length": "short"}],
            "climate_hints": ["tundra", "periglacial", "frozen-ground"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "climate_zone": "frozen", "terrain_style": "tundra"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["tundra", "frozen", "periglacial", "苔原", "冻土"],
    },
    {
        "id": "canyon-country-single",
        "name": "峡谷大陆",
        "description": "大陆被多条深切峡谷切割，V形谷河网密布，起伏剧烈。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.44}],
            "mountains": [{"location": "north", "height": 0.78, "orientation": "east-west"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}, {"region": "south", "length": "long"}],
            "climate_hints": ["canyon", "gorge", "steep-valley"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "terrain_style": "canyon"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 1, "forbid_cross_cut": True},
        "tags": ["canyon", "gorge", "峡谷", "深切", "V形谷"],
    },
    {
        "id": "mediterranean-temperate",
        "name": "地中海式内海",
        "description": "内海横贯中央两侧各一块大陆，夏季干热冬季温和多雨。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.34}, {"position": "south", "size": 0.38}],
            "mountains": [{"location": "north", "height": 0.82, "orientation": "east-west"}],
            "inland_seas": [{"position": "center", "connection": "west strait"}],
            "island_chains": [],
            "peninsulas": [{"location": "north", "size": 0.12}, {"location": "south", "size": 0.1}],
            "river_hints": [{"region": "north", "length": "medium"}, {"region": "south", "length": "medium"}],
            "climate_hints": ["mediterranean", "dry-summer", "inland-sea"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland", "climate_zone": "mediterranean"},
        },
        "topology_intent": {"kind": "central_enclosed_inland_sea", "target_water_component_count": 1, "forbid_cross_cut": True},
        "tags": ["mediterranean", "inland-sea", "temperate", "地中海气候"],
    },
    {
        "id": "rift-valley-continent",
        "name": "裂谷大陆",
        "description": "大陆内部被地壳拉伸出巨大裂谷，两侧高原隆起。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.5}],
            "mountains": [{"location": "west", "height": 0.82, "orientation": "north-south"}, {"location": "east", "height": 0.82, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}],
            "climate_hints": ["rift", "graben", "extensional"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "terrain_style": "rift"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 3, "target_water_component_count": 1, "forbid_cross_cut": False},
        "tags": ["rift", "graben", "裂谷", "地堑"],
    },
    {
        "id": "karst-terrain-continent",
        "name": "喀斯特溶蚀大陆",
        "description": "石灰岩大陆遍布溶蚀洼地、天坑和地下河系统。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.42}],
            "mountains": [{"location": "north", "height": 0.6, "orientation": "east-west"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "center", "length": "short"}, {"region": "south", "length": "medium"}],
            "climate_hints": ["karst", "dissolution", "化学风化"],
            "profile": {"layout_template": "single_island", "sea_style": "open", "terrain_style": "karst"},
        },
        "topology_intent": {"kind": "single_island", "target_land_component_count": 3, "target_water_component_count": 2, "forbid_cross_cut": False},
        "tags": ["karst", "溶蚀", "天坑", "喀斯特"],
    },
    {
        "id": "boreal-temperate-split",
        "name": "寒温南北大陆",
        "description": "北方针叶林冻土，南方阔叶林温带，中间开阔海分隔。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.34}, {"position": "south", "size": 0.36}],
            "mountains": [{"location": "south", "height": 0.74, "orientation": "east-west"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [{"location": "south", "size": 0.1}],
            "river_hints": [{"region": "north", "length": "short"}, {"region": "south", "length": "long"}],
            "climate_hints": ["north-boreal", "south-temperate", "forest-zone"],
            "profile": {"layout_template": "split_north_south", "sea_style": "open", "climate_zone": "subpolar-temperate"},
        },
        "topology_intent": {"kind": "two_continents_with_rift_sea", "target_land_component_count": 2, "target_water_component_count": 1, "forbid_cross_cut": True, "must_disconnect_pairs": [["north", "south"]]},
        "tags": ["split", "boreal", "taiga", "temperate", "针叶林"],
    },
]
