from __future__ import annotations


DEFAULT_RECIPES: list[dict] = [
    {
        "id": "west-east-open-ocean",
        "name": "东西双大陆开海",
        "description": "一东一西两块大陆，中间被开阔海洋隔开，像双大陆之间的外海走廊。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.42}, {"position": "east", "size": 0.42}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["open-ocean"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "tags": ["split", "open-sea", "dual-continent"],
    },
    {
        "id": "west-east-inland-sea",
        "name": "东西双大陆内海",
        "description": "一东一西两块大陆，中间是被陆缘包裹的内海，只通过狭窄海峡与外海连通。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.38}, {"position": "east", "size": 0.38}],
            "mountains": [],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["inland-sea"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "tags": ["split", "inland-sea", "mediterranean"],
    },
    {
        "id": "single-island-continent",
        "name": "单大陆环海",
        "description": "一块四面环海的大陆，海岸线曲折但整体孤立。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.4}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["single-island"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "tags": ["island", "single-continent", "四面环海", "环海大陆"],
    },
    {
        "id": "north-south-continental-split",
        "name": "南北双大陆",
        "description": "一南一北两块大陆，中间被海域分开。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.4}, {"position": "south", "size": 0.4}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["north-south-split"],
            "profile": {"layout_template": "split_north_south", "sea_style": "open"},
        },
        "tags": ["north-south", "open-sea"],
    },
    {
        "id": "east-continent-mountains",
        "name": "东部大陆山脉",
        "description": "东部大陆有一条明显山脉，西部大陆较平缓。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.4}, {"position": "east", "size": 0.42}],
            "mountains": [{"location": "east", "height": 0.9, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "east", "length": "long"}],
            "climate_hints": ["orographic-east"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "tags": ["mountains", "east"],
    },
    {
        "id": "north-rim-mountains-inland",
        "name": "内海北缘山脉",
        "description": "中部内海北缘有山脉，像围绕内海的山系边界。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.36}, {"position": "east", "size": 0.36}],
            "mountains": [{"location": "north", "height": 0.88, "orientation": "east-west"}],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["inland-basin", "north-rim"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "tags": ["inland-sea", "north-mountains"],
    },
    {
        "id": "archipelago-tropical",
        "name": "热带群岛",
        "description": "大片群岛分布在暖湿海域，岛链密集。",
        "world_plan": {
            "continents": [],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [{"position": "center", "density": 0.78}, {"position": "southeast", "density": 0.64}],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["tropical", "archipelago"],
            "profile": {"layout_template": "archipelago", "sea_style": "open"},
        },
        "tags": ["archipelago", "tropical"],
    },
    {
        "id": "supercontinent-arid-interior",
        "name": "超大陆干旱腹地",
        "description": "单一超大陆占据中心，内陆干旱，边缘湿润。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.62}],
            "mountains": [{"location": "west", "height": 0.82, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "east", "length": "short"}],
            "climate_hints": ["arid", "supercontinent"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open"},
        },
        "tags": ["supercontinent", "arid"],
    },
    {
        "id": "west-peninsula-strait",
        "name": "半岛与海峡",
        "description": "西部大陆伸出半岛，形成狭窄海峡连接内海和外海。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.44}, {"position": "east", "size": 0.34}],
            "mountains": [],
            "inland_seas": [{"position": "center", "connection": "east ocean"}],
            "island_chains": [],
            "peninsulas": [{"location": "west", "size": 0.18}],
            "river_hints": [],
            "climate_hints": ["strait"],
            "profile": {"layout_template": "mediterranean", "sea_style": "strait"},
        },
        "tags": ["peninsula", "strait"],
    },
    {
        "id": "cold-northland",
        "name": "寒冷北境",
        "description": "北部大片大陆，寒冷而有冰雪边缘。",
        "world_plan": {
            "continents": [{"position": "north", "size": 0.46}],
            "mountains": [{"location": "northwest", "height": 0.76, "orientation": "arc"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["frozen"],
            "profile": {"layout_template": "default", "sea_style": "open"},
        },
        "tags": ["north", "cold"],
    },
    {
        "id": "east-west-open-sea-north-mountains",
        "name": "开海外加北山",
        "description": "东西两块大陆被开阔海域隔开，但主要山脉位于北部高纬地带，而非某一块大陆腹地。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.41}, {"position": "east", "size": 0.41}],
            "mountains": [{"location": "north", "height": 0.86, "orientation": "east-west"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "north", "length": "short"}],
            "climate_hints": ["open-ocean", "north-rim"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "tags": ["split", "open-sea", "north-mountains", "北部有山脉", "北缘山脉"],
    },
    {
        "id": "east-west-open-sea-west-mountains",
        "name": "开海外加西山",
        "description": "东西两块大陆之间是开海，主要山脉落在西部大陆。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.43}, {"position": "east", "size": 0.39}],
            "mountains": [{"location": "west", "height": 0.88, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "west", "length": "long"}],
            "climate_hints": ["open-ocean", "west-orogen"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "tags": ["split", "open-sea", "west-mountains"],
    },
    {
        "id": "east-west-inland-sea-east-mountains",
        "name": "内海外加东山",
        "description": "中部是内海，东部大陆边缘有明显山脉。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.37}, {"position": "east", "size": 0.39}],
            "mountains": [{"location": "east", "height": 0.9, "orientation": "north-south"}],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "east", "length": "long"}],
            "climate_hints": ["inland-sea", "east-orogen"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "tags": ["inland-sea", "east-mountains"],
    },
    {
        "id": "east-west-inland-sea-south-mountains",
        "name": "内海外加南山",
        "description": "东西大陆之间是内海，南缘有一条东西向山脉。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.36}, {"position": "east", "size": 0.36}],
            "mountains": [{"location": "south", "height": 0.84, "orientation": "east-west"}],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["inland-sea", "south-rim"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "tags": ["inland-sea", "south-mountains"],
    },
    {
        "id": "single-island-west-peninsula",
        "name": "单岛西半岛",
        "description": "单块环海大陆向西伸出半岛，主体仍然保持岛状。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.39}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [{"location": "west", "size": 0.18}],
            "river_hints": [],
            "climate_hints": ["single-island", "west-peninsula"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "tags": ["single-island", "peninsula", "west"],
    },
    {
        "id": "single-island-east-mountains",
        "name": "单岛东山脉",
        "description": "环海单大陆，东侧靠海有山脉抬升。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.4}],
            "mountains": [{"location": "east", "height": 0.86, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}],
            "climate_hints": ["single-island", "east-orogen"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "tags": ["single-island", "east-mountains"],
    },
    {
        "id": "archipelago-northeast-chain",
        "name": "东北岛链",
        "description": "东北方向存在明显岛链，其余海域较空旷。",
        "world_plan": {
            "continents": [],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [{"position": "northeast", "density": 0.82}],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["archipelago", "northeast-chain"],
            "profile": {"layout_template": "archipelago", "sea_style": "open"},
        },
        "tags": ["archipelago", "northeast"],
    },
    {
        "id": "archipelago-southwarm-chain",
        "name": "南方暖海群岛",
        "description": "南方暖海中散布连续群岛，北部相对空旷。",
        "world_plan": {
            "continents": [],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [{"position": "south", "density": 0.74}, {"position": "southeast", "density": 0.68}],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["archipelago", "tropical", "south-seas"],
            "profile": {"layout_template": "archipelago", "sea_style": "open"},
        },
        "tags": ["archipelago", "south", "tropical"],
    },
    {
        "id": "supercontinent-central-mountains",
        "name": "超大陆中央山系",
        "description": "超大陆中心有一条大型山系，控制河流和气候分界。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.64}],
            "mountains": [{"location": "center", "height": 0.92, "orientation": "arc"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "west", "length": "long"}, {"region": "east", "length": "long"}],
            "climate_hints": ["supercontinent", "central-mountains"],
            "profile": {"layout_template": "supercontinent", "sea_style": "open"},
        },
        "tags": ["supercontinent", "central-mountains"],
    },
    {
        "id": "frozen-inland-basin",
        "name": "寒冷内海盆地",
        "description": "高纬度内海被寒冷大陆包围，边缘有雪线山脉。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.35}, {"position": "east", "size": 0.35}],
            "mountains": [{"location": "north", "height": 0.8, "orientation": "east-west"}],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["frozen", "inland-sea"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "tags": ["frozen", "inland-sea", "north"],
    },
    {
        "id": "arid-west-east-open-ocean",
        "name": "干旱双大陆开海",
        "description": "东西两块大陆之间是开海，但两侧大陆整体偏干旱。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.4}, {"position": "east", "size": 0.4}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["open-ocean", "arid"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open", "palette_hint": "arid"},
        },
        "tags": ["open-sea", "arid", "split"],
    },
    {
        "id": "east-west-open-sea-east-mountains",
        "name": "开海外加东山",
        "description": "东西双大陆之间是开阔外海，东部大陆沿海有明显山脉。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.4}, {"position": "east", "size": 0.42}],
            "mountains": [{"location": "east", "height": 0.9, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "east", "length": "long"}],
            "climate_hints": ["open-ocean", "east-orogen"],
            "profile": {"layout_template": "split_east_west", "sea_style": "open"},
        },
        "tags": ["open-sea", "east-mountains", "split", "东部大陆有山脉"],
    },
    {
        "id": "east-west-inland-sea-north-mountains",
        "name": "内海外加北山",
        "description": "东西双大陆围绕中央内海，北缘有一条山脉控制内海气候。",
        "world_plan": {
            "continents": [{"position": "west", "size": 0.36}, {"position": "east", "size": 0.37}],
            "mountains": [{"location": "north", "height": 0.88, "orientation": "east-west"}],
            "inland_seas": [{"position": "center", "connection": "strait"}],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["inland-sea", "north-rim"],
            "profile": {"layout_template": "mediterranean", "sea_style": "inland"},
        },
        "tags": ["inland-sea", "north-mountains", "split", "北部有山脉", "中间有内海"],
    },
    {
        "id": "single-island-east-peninsula",
        "name": "单岛东半岛",
        "description": "单块环海大陆向东侧延伸出半岛，主体仍保持岛状大陆。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.39}],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [{"location": "east", "size": 0.18}],
            "river_hints": [],
            "climate_hints": ["single-island", "east-peninsula"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "tags": ["single-island", "peninsula", "east", "东侧伸出半岛", "四面环海"],
    },
    {
        "id": "single-island-west-mountains",
        "name": "单岛西山脉",
        "description": "环海单大陆的西侧有山脉，整体仍是孤立大陆。",
        "world_plan": {
            "continents": [{"position": "center", "size": 0.4}],
            "mountains": [{"location": "west", "height": 0.86, "orientation": "north-south"}],
            "inland_seas": [],
            "island_chains": [],
            "peninsulas": [],
            "river_hints": [{"region": "center", "length": "long"}],
            "climate_hints": ["single-island", "west-orogen"],
            "profile": {"layout_template": "single_island", "sea_style": "open"},
        },
        "tags": ["single-island", "west-mountains", "西侧有山脉", "四面环海"],
    },
    {
        "id": "archipelago-northeast-southwarm",
        "name": "东北岛链与南方暖海",
        "description": "南方暖海中散布群岛，东北方向另有一条更密集的岛链。",
        "world_plan": {
            "continents": [],
            "mountains": [],
            "inland_seas": [],
            "island_chains": [{"position": "south", "density": 0.7}, {"position": "northeast", "density": 0.84}],
            "peninsulas": [],
            "river_hints": [],
            "climate_hints": ["archipelago", "tropical", "northeast-chain"],
            "profile": {"layout_template": "archipelago", "sea_style": "open"},
        },
        "tags": ["archipelago", "tropical", "northeast"],
    },
]
